### ISSUE TITLE
Many 'View docs' links are bad on https://cloud.ibm.com/docs/services/key-protect?topic=key-protect-integrate-services

### ISSUE THREAD

**Issue by snorthov** [ibm-cloud-docs/key-protect#1]
https://cloud.ibm.com/docs/services/key-protect?topic=key-protect-integrate-services

![image](https://user-images.githubusercontent.com/11139850/67802411-726c9080-fa61-11e9-9b26-86c3584109d7.png)

1) Click on 'View docs'.  
2) The link is bad.  
3) Links are also bad for ICD Redis and other 'Databases'.

**Comment by ccbarragan** [comment]
@snorthov Whoops, sorry for our late response!

We fixed these up some time ago. Thank you for the heads up.
