### ISSUE TITLE
Documentation: API Docs link does not work. 

### ISSUE THREAD

**Issue by marek5050** [ibm-cloud-docs/key-protect#2]
The navigation link pointing at the API reference shows an error

https://cloud.ibm.com/apidocs/key-protect

![image](https://user-images.githubusercontent.com/6081895/127908888-a0f585dd-1614-4dba-ba04-50859952f304.png)

![image](https://user-images.githubusercontent.com/6081895/127908927-571cc070-6598-47d7-bda2-e6c5243a6abf.png)

**Comment by jenschlot** [comment]
@marek5050 Sorry for that glitch. We had an outage, but those API docs are back up again.
